version: '3.1'

services:
  api:
    image: dmitry093/cars:develop
    ports:
      - "8084:8080"
    depends_on:
      - "db"
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpasswd
      MYSQL_USER: user
      MYSQL_PASSWORD: 1234
      MYSQL_DATABASE: cars
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d
    ports:
      - "3309:3306"